### ISSUE TITLE
Извиняюсь

### ISSUE THREAD

**Issue by secretstation** [DashaMilitskaya/DriverSystemInfo#1]
Извиняюсь, случайно нашел ваш репозиторий, можно поинтересоваться это где в каком универе учат такому на лабах (в хорошем смысле)
Работа с ssdt впечатляет.

Sysprog2Lab1)

**Comment by DashaMilitskaya** [comment]
Вауктотоещётакимзанимется :)
https://www.csu.ru/ 
ЧелГу, Кафедра компьютерной безопасности.
А с какой целью интересуетесь?

**Comment by DaryaC-code** [comment]
Вауктотоещётакимзанимется :)
https://www.csu.ru/
ЧелГу, Кафедра компьютерной безопасности.
А с какой целью интересуетесь?

> Извиняюсь, случайно нашел ваш репозиторий, можно поинтересоваться это где в каком универе учат такому на лабах (в хорошем смысле) Работа с ssdt впечатляет.
> 
> Sysprog2Lab1)

**Comment by recoil24** [comment]
@IvankoEanko чё в хуй сказал, ответь если мать шлюха или промолчи если батя пидор.

**Comment by digitalpurpl3e** [comment]
за че хейт
